### ISSUE TITLE
markLogicDatasetGraph.find(null,null,null,null) throws nullPointerException

### ISSUE THREAD

**Issue by grechaw** [marklogic/marklogic-jena#3]
From @kkanthet  originally

``` java
Iterator<Quad> quads = markLogicDatasetGraph.find(null,null,null,null);
throws NullPointerException

Expecting to return all the quads.

StackTrace::
java.lang.NullPointerException
 at com.marklogic.semantics.jena.MarkLogicDatasetGraph.skolemize(MarkLogicDatasetGraph.java:155)
 at com.marklogic.semantics.jena.MarkLogicDatasetGraph.selectTriplesInGraph(MarkLogicDatasetGraph.java:217)
 at com.marklogic.semantics.jena.MarkLogicDatasetGraph.findInDftGraph(MarkLogicDatasetGraph.java:247)
 at com.hp.hpl.jena.sparql.core.DatasetGraphBaseFind.findAny(DatasetGraphBaseFind.java:70)
 at com.hp.hpl.jena.sparql.core.DatasetGraphBaseFind.find(DatasetGraphBaseFind.java:49)
 at com.marklogic.jena.functionaltests.JenaGraphTests.test001Crud_admin(JenaGraphTests.java:144)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:497)
 at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
 at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
 at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
 at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
 at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
 at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
 at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
 at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
 at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
 at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
 at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
 at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
 at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
 at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
 at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
 at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
 at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
 at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
 at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
 at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
 at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
 at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
 at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)


```

**Comment by grechaw** [comment]
Same issue with markLogicDatasetGraph.deleteAny(node, null, null, null);

**Comment by kkanthet** [comment]
Same nullpointer with findNG when subject is null

``` java
markLogicDatasetGraph.findNG(NodeFactory.createURI("http://originalGraph1"), Node.ANY, NodeFactory.createURI("http://www.w3.org/1999/02/22-rdf-syntax-ns#type1"), null);

java.lang.NullPointerException
    at com.marklogic.semantics.jena.MarkLogicDatasetGraph.skolemize(MarkLogicDatasetGraph.java:155)
    at com.marklogic.semantics.jena.MarkLogicDatasetGraph.selectTriplesInGraph(MarkLogicDatasetGraph.java:218)
    at com.marklogic.semantics.jena.MarkLogicDatasetGraph.findInSpecificNamedGraph(MarkLogicDatasetGraph.java:258)
    at com.hp.hpl.jena.sparql.core.DatasetGraphBaseFind.findNG(DatasetGraphBaseFind.java:59)
    at com.marklogic.jena.functionaltests.JenaGraphTests.test001AddRead_AdminUser(JenaGraphTests.java:357)



```

**Comment by grechaw** [comment]
I think I'm good with a fix for this.

**Comment by kkanthet** [comment]
Verified that nullPointer is not longer thrown and Find and Delete are working as expected when passed in null
